"""Create PRs in clinic-gitops-config via GitHub API."""

from __future__ import annotations

import base64
import json
import logging
from dataclasses import dataclass
from typing import Any

import httpx

__all__ = ["GitHubPRCreator", "PRResult"]

logger = logging.getLogger(__name__)

_MAX_RETRIES = 2


@dataclass(frozen=True)
class PRResult:
    pr_number: int
    pr_url: str
    branch: str


class GitHubPRCreator:
    """Creates HMAC-signed execution plans as PRs in the gitops-config repo."""

    def __init__(
        self,
        token: str,
        owner: str = "julian-najas",
        repo: str = "clinic-gitops-config",
    ) -> None:
        self._token = token
        self._owner = owner
        self._repo = repo
        self._client = httpx.AsyncClient(
            base_url="https://api.github.com",
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=30.0,
        )

    @property
    def _repo_path(self) -> str:
        return f"/repos/{self._owner}/{self._repo}"

    async def create_plan_pr(
        self,
        plan_manifest: dict[str, Any],
        environment: str,
        branch_name: str,
    ) -> PRResult:
        """Create a branch, commit the plan, and open a PR.

        Flow:
            1. Get default branch HEAD SHA
            2. Create feature branch
            3. Commit plan JSON file
            4. Create Pull Request
        """
        plan_id = plan_manifest.get("plan_id", "unknown")
        file_path = f"environments/{environment}/plans/{plan_id}.json"

        # 1 ── Get base SHA ────────────────────────────────────────
        base_sha = await self._get_default_branch_sha()

        # 2 ── Create branch ───────────────────────────────────────
        await self._create_branch(branch_name, base_sha)

        # 3 ── Commit plan file ────────────────────────────────────
        content_b64 = base64.b64encode(
            json.dumps(plan_manifest, indent=2).encode()
        ).decode()

        await self._create_file(
            path=file_path,
            content_b64=content_b64,
            branch=branch_name,
            message=(
                f"proposal: add execution plan {plan_id[:8]}\n\n"
                f"Risk level: {plan_manifest.get('risk_level', 'unknown')}\n"
                f"Environment: {environment}\n"
                f"Actions: {len(plan_manifest.get('actions', []))}\n\n"
                f"Auto-generated by clinical-agentic-control-plane."
            ),
        )

        # 4 ── Create PR ──────────────────────────────────────────
        pr = await self._create_pull_request(
            head=branch_name,
            title=(
                f"proposal: {plan_id[:8]} "
                f"({plan_manifest.get('risk_level', '?')} risk)"
            ),
            body=self._build_pr_body(plan_manifest, environment),
        )

        return PRResult(
            pr_number=pr["number"],
            pr_url=pr["html_url"],
            branch=branch_name,
        )

    # ── GitHub API helpers ────────────────────────────────────────

    async def _get_default_branch_sha(self) -> str:
        resp = await self._request(
            "GET", f"{self._repo_path}/git/ref/heads/main"
        )
        return resp["object"]["sha"]

    async def _create_branch(self, name: str, sha: str) -> None:
        await self._request(
            "POST",
            f"{self._repo_path}/git/refs",
            json={"ref": f"refs/heads/{name}", "sha": sha},
        )

    async def _create_file(
        self,
        path: str,
        content_b64: str,
        branch: str,
        message: str,
    ) -> None:
        await self._request(
            "PUT",
            f"{self._repo_path}/contents/{path}",
            json={
                "message": message,
                "content": content_b64,
                "branch": branch,
            },
        )

    async def _create_pull_request(
        self, head: str, title: str, body: str
    ) -> dict[str, Any]:
        return await self._request(
            "POST",
            f"{self._repo_path}/pulls",
            json={
                "title": title,
                "body": body,
                "head": head,
                "base": "main",
            },
        )

    async def _request(
        self,
        method: str,
        url: str,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """HTTP request with retries."""
        last_exc: Exception | None = None
        for attempt in range(_MAX_RETRIES + 1):
            try:
                resp = await self._client.request(method, url, **kwargs)
                resp.raise_for_status()
                return resp.json()  # type: ignore[no-any-return]
            except httpx.HTTPStatusError as exc:
                last_exc = exc
                # Don't retry on conflicts or validation errors
                if exc.response.status_code in (409, 422):
                    raise
                if attempt < _MAX_RETRIES:
                    logger.warning(
                        "GitHub API %s %s failed (attempt %d): %s",
                        method, url, attempt + 1, exc,
                    )
            except httpx.HTTPError as exc:
                last_exc = exc
                if attempt < _MAX_RETRIES:
                    logger.warning(
                        "GitHub API %s %s error (attempt %d): %s",
                        method, url, attempt + 1, exc,
                    )
        raise last_exc  # type: ignore[misc]

    @staticmethod
    def _build_pr_body(plan: dict[str, Any], env: str) -> str:
        actions = plan.get("actions", [])
        action_lines = "\n".join(
            f"  - {a.get('action_type', '?')} via {a.get('channel', '?')} "
            f"at {a.get('scheduled_at', 'TBD')}"
            for a in actions
        )
        return (
            f"## Execution Plan Proposal\n\n"
            f"**Plan ID:** `{plan.get('plan_id', '?')}`\n"
            f"**Environment:** `{env}`\n"
            f"**Risk level:** `{plan.get('risk_level', '?')}`\n"
            f"**Actions:**\n{action_lines}\n\n"
            f"**HMAC signed:** {'✅' if plan.get('hmac_signature') else '❌'}\n\n"
            f"---\n"
            f"*Auto-generated by `clinical-agentic-control-plane`.*\n"
            f"*CI will verify HMAC signature and schema compliance before merge.*"
        )

    async def close(self) -> None:
        await self._client.aclose()
